version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

#  ApplicationStop:
#    - location: ./deploy_server_applicationStop.sh
#      runas: ubuntu

  ApplicationStart:
    - location: ./deploy_server_applicationStart.sh
      timeout: 180
      runas: ubuntu