version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/client
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:


  ApplicationStart:
    - location: ./deploy_client.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: ./deploy_server_applicationStart.sh
      timeout: 180
      runas: ubuntu