name: travel develop server CI/CD

on:
  push:
    branches: [ server_develop_test ]
  pull_request:
    branches: [ server_develop_test ]

env:
  S3_BUCKET_NAME: travel-deploy

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
#     - name: Grant execute permission for gradlew
#       run: chmod +x ./server/travelDiary/travelDiary/gradlew
    
#     - name: Build with Gradle
#       run: ./gradlew clean build
#       working-directory: "./server/travelDiary/travelDiary"
      
      # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy file
      run: cp ./ ./deploy

    - name: Make zip file
      run: zip -r ./travel.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./travel.zip s3://trevel-repo/
      
